name: example
description: "Demonstration application for bus_seat_plan v3.0 package."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bus_seat_plan:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
